POST http://localhost:3000/api/usecases HTTP/1.1
content-type: application/json

{
    "action": "REGISTER_USER", 
    "payload": {
        "username": "asimsheikh2@hello.com",
        "password": "asim"
    }
}

### 

POST http://localhost:3000/api/usecases HTTP/1.1
content-type: application/json

{
    "action": "ADD_BLOG_POST", 
    "payload": {
        "date": "2022-10-12",
        "blog": "There is nothing to say here....", 
        "username": "asimsheikh@hello.com"
    }
}

### 

POST http://localhost:3000/api/usecases HTTP/1.1
content-type: application/json

{
    "action": "GET_BLOG_POSTS", 
    "payload": {
        "username": "asimsheikh@hello.com"
    }
}