import { signOut, signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const { data: session } = useSession();
  console.log('In the Home page with session: ', session);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Hello World</div>
      {session ? (
        <div>Welcome to our site again {session.username}</div>
      ) : (
        <></>
      )}
      <div>
        {session ? (
          <button className='bg-blue-400 py-2 px-4' onClick={() => signOut()}>
            Logout
          </button>
        ) : (
          <button
            className='bg-blue-400 py-2 px-4'
            onClick={() => signIn('credentials')}
          >
            SignIn
          </button>
        )}
      </div>
    </div>
  );
}
